// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/7/2026, 10:15:33 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/plugins/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/composables/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/composables/**/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/types/components/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/types/components/**/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/utils/**/*.{js,ts,mjs}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lukasviliams/Desktop/development/personal/front-end-hiring-assigment/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;